services:
  dxspider:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - "linux/arm64"
        - "linux/amd64"
      args:
        - SPIDER_VERSION=${CLUSTER_DXSPIDER_BRANCH}
        - SPIDER_USERNAME=${CLUSTER_DB_USER}
    privileged: true
    environment:
      - SPIDER_INSTALL_DIR=/spider
      - CLUSTER_CALLSIGN=${CLUSTER_CALLSIGN}
      - CLUSTER_LOCATOR=${CLUSTER_LOCATOR}
      - CLUSTER_QTH=${CLUSTER_QTH}
      - CLUSTER_SYSOP_NAME=${CLUSTER_SYSOP_NAME}
      - CLUSTER_SYSOP_CALLSIGN=${CLUSTER_SYSOP_CALLSIGN}
      - CLUSTER_SYSOP_EMAIL=${CLUSTER_SYSOP_EMAIL}
      - CLUSTER_SYSOP_BBS_ADDRESS=${CLUSTER_SYSOP_BBS_ADDRESS}
      - CLUSTER_LATITUDE=${CLUSTER_LATITUDE}
      - CLUSTER_LONGITUDE=${CLUSTER_LONGITUDE}
      - SPIDER_USERNAME=${CLUSTER_DB_USER}
      - CLUSTER_DSN=dbi:mysql:${CLUSTER_DB_NAME}:${CLUSTER_DB_HOSTNAME}:${CLUSTER_DB_PORT}
      - CLUSTER_DBUSER=${CLUSTER_DB_USER}
      - CLUSTER_DBPASS=${CLUSTER_DB_PASS}
      - CLUSTER_PORT=${CLUSTER_PORT}
    healthcheck:
      test: ["CMD", "nc", "-z", "-v", "localhost", "${CLUSTER_PORT}"]
      interval: 10s
      start_period: 5s
      retries: 3
      timeout: 60s
    restart: always
    volumes:
      - /srv/docker/dxspider/startup:/spider/scripts/startup:rw
      - /srv/docker/dxspider/crontab:/spider/local_cmd/crontab:rw
      - /srv/docker/dxspider/connect:/spider/connect:rw
      - /srv/docker/dxspider/motd:/spider/local_data/motd:rw
      - /srv/docker/dxspider/local_data:/spider/local_data:rw
      - /srv/docker/dxspider/cmd:/spider/cmd:rw
      - /srv/docker/dxspider/msg:/spider/msg:rw  
    ports:
      - ${CLUSTER_PORT}:${CLUSTER_PORT}
    expose:
      - ${CLUSTER_PORT}
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      database: {}

networks:
  database:
    external: true

